[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[build.environment]
  VITE_SITE_URL = "https://www.kevinang.com"

# [context.production]
#   environment = { VITE_SITE_URL = "https://www.kevinang.com" }